### ISSUE TITLE
Body_Error returned when Content-Length not specified in response header

### ISSUE THREAD

**Issue by dogue** [laytan/odin-http#13]
Below are the returned headers for a JSON API I'm trying to request. The response is successful but the server does not return a Content-Length field in the response header which is causing the library to fail on retrieving the response body.

Can the library be made fault-tolerant for poorly-formed response headers or should I look into finding a different API to use? I have no control over the API in this instance.

If it helps, `https://random-word-api.herokuapp.com/home` is the offending service.

```
Status: OK
Headers: map[content-type="application/json", date="Mon, 11 Sep 2023 03:46:11 GMT", access-control-allow-origin="*", via="1.1 vegur", server="Cowboy", connection="close"]
Error retrieving body: No_Length
```

Edit: I was able to find the repo for the API in question. I submitted [this issue](https://github.com/RazorSh4rk/random-word-api/issues/32) over there. If handling malformed headers is outside the scope of this library, feel free to close this issue.

**Comment by laytan** [comment]
Hello,

After reading [the RFC](https://www.rfc-editor.org/rfc/rfc7230#section-3.3.3) again, their response is technically valid, because the server does not have persistent connections (they send the "connection: close" header), the body is everything they send until they close the connection.

I will make the changes to support this.

**Comment by laytan** [comment]
Should now work on the latest commit (e310f9e3e16d80ff517b98add96d5b68e58f50d0), please reopen if it doesn't
